### ISSUE TITLE
Can't seem to trigger snippets?

### ISSUE THREAD

**Issue by enkota** [frkcn/vue-snippets#1]
Hey, thanks for making this extension. When trying to trigger any snippet within a Vue file it doesn't seem to work. On VSCode I would simply type `vfor` for example and it would work. Is this still working on the latest Nova?

**Comment by frkcn** [comment]
Hi,

This project still in development phase. I don't try and not sure how it's work but you can try this https://github.com/tommasongr/nova-vue.
